### ISSUE TITLE
Linux&Docker 채점

### ISSUE THREAD

**Issue by hengyinayo** [wjddid000624/Ybigta_assignment#1]
![101_5516a02617ec7_2133](https://github.com/wjddid000624/Ybigta_assignment/assets/90566079/b3860952-d28b-4288-ba3b-445fd9e14909)
과제 열심히 해주셔서 정말 감사합니다!
수고 많으셨어요! 남은 교육세션 홧팅!

(퍼펙트!

**Comment by wjddid000624** [comment]
감사합니다 :)
